language: node_js
node_js:
    - 10

install:
    - npm install

script:
    - npm run build

jobs:
    include:
        - stage: deploy
          on:
              branch: master
          deploy:
              provider: npm
              edge: true
              email: '$NPM_EMAIL'
              api_key: '$NPM_API_TOKEN'
